######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 1 14:46:49 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += datetime.h msort.h multiwin.h tweet.h twiteng.h user.h
SOURCES += datetime.cpp multiwin.cpp tweet.cpp twiteng.cpp twitter.cpp user.cpp 
