

remdup: remdup.cpp
	g++ -g -Wall remdup.cpp -o remdup

alistint: alistint.cpp alistint.h
	g++ -g -Wall alistint.cpp alistint.h -o alistint

testAddToEmptyList: llistint.cpp llistint.h testAddToEmptyList.cpp 
	g++ -g -Wall llistint.cpp llistint.h testAddToEmptyList.cpp  -o testAddToEmptyList

testAlistInt: alistint.cpp alistint.h testAlistInt.cpp
	g++ -g -Wall alistint.cpp alistint.h testAlistInt.cpp -o testAlistInt

laundry: stackint.cpp laundry.cpp stackint.h 
	g++ -g stackint.cpp laundry.cpp llistint.cpp -o laundry

stackint: stackint.cpp stackint.h
	g++ -g -Wall stackint.cpp stackint.h -o stackint