testBinarySearch: testBinarySearch.cpp bst.h
	g++ -g -Wall testBinarySearch.cpp -o testBinarySearch

rbbstTest: rbbstTest.cpp rbbst.h bst.h
	g++ -g -Wall rbbstTest.cpp -o rbbstTest

BooleanSat: BooleanSat.cpp rbbst.h bst.h
	g++ -g -Wall BooleanSat.cpp -o BooleanSat